### ISSUE TITLE
FW, ninja-Dsim-like, R1, R2, Xanthias and Y consensus sequences

### ISSUE THREAD

**Issue by portiahollyoak** [bergmanlab/transposons#22]
Hi,

Thank you for maintaining this repository, it has been extremely useful. 
I am working on detecting transposable element insertions in Drosophila melanogaster samples, which requires TE consensus sequences. The vast majority of TEs annotated in the Drosophila melanogaster genome release 6 from Flybase have corresponding consensus sequences in your set but there seem to be a few that are missing: FW, ninja-Dsim-like, R1, R2, Xanthias, Y.
Would it be possible to add these to the set/ is there a reason for why they are not included?

Many thanks,
Portia Hollyoak

**Comment by portiahollyoak** [comment]
Thank you for responding so quickly. 
I have matched transposable element family names found in the Flybase drosophila melanogaster reference genome release 6.10 genome annotations with their symbols on Flybase, their Fbte and their IDs given in your updated set. I was wondering if this might help you.
[TE_names_fbte_id.pdf](https://github.com/cbergman/transposons/files/329890/TE_names_fbte_id.pdf)

**Comment by cbergman** [comment]
Hi Portia -

Thanks for posting this issue. I'm still working on making fixes based on your suggestions and will reply more in full as soon as I can. In the mean time, could you post the data in TE_names_fbte_id.pdf as a text file, maybe somewhere in your github account or as a gist? Also, could you point me to where you  saw the Y-element referred to in a paper. I think this element may be a ghost name for another TE.

Best regards,
Casey

**Comment by portiahollyoak** [comment]
Hi Casey,

I have added the TE_names_fbte_id file to my github repository, TE-Consensus-Sequences. Regarding the Y-element, it is on [Flybase](http://flybase.org/reports/FBte0001427.html), but there does not seem to be any papers referencing it, so you may be correct.

Many thanks,
Portia

**Comment by cbergman** [comment]
Thanks Portia. File referred to in https://github.com/cbergman/transposons/issues/22#issuecomment-228072294 is located at: https://github.com/portiahollyoak/TE-Consensus-Sequences/blob/master/TE_names_fbte_id.tsv

**Comment by cbergman** [comment]
Hi Portia

I have reviewed all of your queries, some of which it appears are synonym issues and some of which led to improvements in the EMBL file, so thanks for posting this issue. I'll address the six families in question one-by-one (FW, ninja-Dsim-like, R1, R2, Xanthias, Y).

- FW: this TE is a synonym of the F-element. See the "Synonyms and Secondary IDs" section of the FBte page for the F-element: http://flybase.org/reports/FBte0000005.html
- ninja-Dsim-like: this is fairly tricky issue that deserves further attention. I tried to articulate the problem here https://github.com/cbergman/transposons/issues/24. In short, ninja-Dsim-like is not in the EMBL file since Dmel\aurora-element and Dsim\ninja are both there. There are legacy annotations in D.melanogaster R6.10 that were obtained using a Dsim\ninja query and were named ninja-Dsim-like in Quesneville at al 2005.
- R1: this TE is a synonym of the R1A1-element. See the "Synonyms and Secondary IDs" section of the FBte page for the R1A1-element http://flybase.org/reports/FBte0000118.html
- R2: this TE is a synonym of the R2-element. See the "Synonyms and Secondary IDs" section of the FBte page for the R2-element: http://flybase.org/reports/FBte0000030.html
- Xanthias: This element was missing from the EMBL file. I have now added it to the current EMBL file using the information inhttp://flybase.org/reports/FBte0001316.html, and it will included in a future update.
- Y: There does not appear to be any evidence that the Y-element is a real TE: http://flybaselb1.uits.indiana.edu/reports/FBte0001427.html. I will suggest that FlyBase deprecate this entry.

I have also done an audit of the TE families you posted in https://github.com/portiahollyoak/TE-Consensus-Sequences/blob/master/TE_names_fbte_id.tsv. I imported this file into the transposons repository https://github.com/cbergman/transposons/tree/master/personal_communications/hollyoak, and compared the FBtes and names from your spreadsheet to the FBtes and names obtained from the current EMBL file. This comparison can be found in https://github.com/cbergman/transposons/blob/master/personal_communications/hollyoak/TE_names_fbte_id_embl_audit.tsv. You do not include several sequences in your spreadsheet (P-element, TAHRE, Helitron, Osvaldo, Penelope). The Dmel\Penelope is likely to be an error, and I am not sure about the reality of Osvaldo, but P-element, TAHRE and Helitron are real. Also, you include HeT-Tag (FBte0001217), which should be considered fragments of Het-A (FBte0000143).

Thanks for bringing these issues to my attention. Adding Xanthias was imporant and this review has prompted several other long-overdue improvements.

Best regards,
Casey
